name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Déclenchement sur push vers la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install  # ou yarn install selon ton projet

      - name: Build Project
        run: npm run build  # ou yarn build si nécessaire

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: "./dist"  # Remplace par le dossier de build
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Auto-deployed via GitHub Actions"
          alias: "latest"
          enable-pull-request-comment: false
          enable-commit-comment: false
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
