name: Run NPM Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Vous pouvez choisir une version différente de Node.js si nécessaire

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
